### ISSUE TITLE
Serverless and axiom-lambda-extension

### ISSUE THREAD

**Issue by mits87** [axiomhq/axiom-lambda-extension#16]
Hi there, 

I'm trying to use your plugin with the serverless framework. 
Basically I'm doing something like:

```
service: app

frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-extra-parameters
  - serverless-offline

package:
  excludeDevDependencies: true
  individually: true
  patterns:
    - '!**/node_modules/@aws-sdk/**'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'dev'}
  stackName: app
  layers:
    axiom:
      path: arn:aws:lambda:${self:provider.region}:694952825951:layer:axiom-extension-arm64:4
      name: axiom-layer
      description: Axiom unlocks observability at any scale.
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE: 1
    LOG_LEVEL: debug
    NODE_ENV: production
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    AXIOM_TOKEN: ${ssm:/${self:provider.stage}/AXIOM_TOKEN}
    AXIOM_DATASET: 'app'

functions:
  api:
    handler: ./src/events/api.handler
    description: 'REST API / GraphQL handler'
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

```

But unfortunately when I'm trying to deploy my lambda (using `sls deploy` command) I'm getting error:
```
Error:
No file matches include / exclude patterns
```

<img width="901" alt="image" src="https://github.com/axiomhq/axiom-lambda-extension/assets/605186/2f6b0179-9eb9-4195-a21d-2f2994a29f57">

Any idea what's wrong?
